### ISSUE TITLE
US-7 Cocktail inpiratie pagina

### ISSUE THREAD

**Issue by steenbokdev** [steenbokdev/de-gouden-draak#6]
Als klant wil ik tijdens het wachten op een bestelling een cocktail inspiratie pagina zien zodat ik een lekker drankje kan bestellen

Gebruik een API om cocktails op te halen bv https://www.thecocktaildb.com/api.php
Laat plaatjes zien van de cocktails
Zorg voor een zoek functie
Zorg voor een filter functie

**Comment by steenbokdev** [comment]
Ik weet niet of met "...zodat ik een lekker drankje kan bestellen" wordt bedoeld dat de cocktails besteld kunnen worden. Heb jij enig idee @linderus?

**Comment by linderus** [comment]
> Ik weet niet of met "...zodat ik een lekker drankje kan bestellen" wordt bedoeld dat de cocktails besteld kunnen worden. Heb jij enig idee [@linderus](https://github.com/linderus)?

Sorry, je berichtje valt mij nu pas op... ik denk dat de manier waarop je het nu hebt gedaan goed is!
